/**
 * Centralized Game Artwork & Metadata Mapping
 * Maps every game ID to its project-owned local artwork, provider, category, badge, and title.
 */

export interface GameArtworkEntry {
  id: number;
  name: string;
  artwork: string;
  provider: string;
  category: string;
  tag?: "HOT" | "NEW" | "JACKPOT";
  rating: number;
  playCount: string;
  supportsFreeSpins?: boolean;
  isMemberOnly?: boolean;
}

export const GAME_ARTWORK_MAP: Record<number, GameArtworkEntry> = {
  312001: {
    id: 312001,
    name: "Aviator",
    artwork: "/images/games/aviator.svg",
    provider: "Spribe",
    category: "minigames",
    tag: "HOT",
    rating: 4.9,
    playCount: "3.2M",
    supportsFreeSpins: false,
  },
  3150300: {
    id: 3150300,
    name: "Fortune Gems 3",
    artwork: "/images/games/fortune_gems_3.svg",
    provider: "JILI",
    category: "slot",
    tag: "HOT",
    rating: 4.8,
    playCount: "1.9M",
    supportsFreeSpins: true,
  },
  3150049: {
    id: 3150049,
    name: "Super Ace",
    artwork: "/images/games/super_ace.svg",
    provider: "JILI",
    category: "slot",
    tag: "HOT",
    rating: 4.9,
    playCount: "2.4M",
    supportsFreeSpins: true,
  },
  3150094: {
    id: 3150094,
    name: "Rummy",
    artwork: "/images/games/rummy.svg",
    provider: "JILI",
    category: "cards",
    tag: "HOT",
    rating: 4.9,
    playCount: "4.1M",
    supportsFreeSpins: false,
  },
  3150124: {
    id: 3150124,
    name: "7up 7down",
    artwork: "/images/games/7up_7down.svg",
    provider: "JILI",
    category: "cards",
    tag: "NEW",
    rating: 4.7,
    playCount: "890K",
    supportsFreeSpins: false,
  },
  3150200: {
    id: 3150200,
    name: "PAPPU",
    artwork: "/images/games/pappu.svg",
    provider: "JILI",
    category: "cards",
    tag: "HOT",
    rating: 4.6,
    playCount: "650K",
    supportsFreeSpins: false,
  },
  3150051: {
    id: 3150051,
    name: "Money Coming",
    artwork: "/images/games/money_coming.svg",
    provider: "JILI",
    category: "slot",
    tag: "JACKPOT",
    rating: 4.9,
    playCount: "5.8M",
    supportsFreeSpins: true,
  },
  2000135: {
    id: 2000135,
    name: "Wild Bounty Showdown",
    artwork: "/images/games/wild_bounty.svg",
    provider: "PG Soft",
    category: "slot",
    tag: "HOT",
    rating: 4.8,
    playCount: "1.2M",
    supportsFreeSpins: false,
  },
  3660003: {
    id: 3660003,
    name: "Chicken Road 2.0",
    artwork: "/images/games/chicken_road_2.svg",
    provider: "INOUT",
    category: "minigames",
    tag: "NEW",
    rating: 4.9,
    playCount: "950K",
    supportsFreeSpins: false,
  },
  3660008: {
    id: 3660008,
    name: "Chicken Road",
    artwork: "/images/games/chicken_road.svg",
    provider: "INOUT",
    category: "minigames",
    tag: "HOT",
    rating: 4.7,
    playCount: "820K",
    supportsFreeSpins: false,
  },
  5008: {
    id: 5008,
    name: "Plinko",
    artwork: "/images/games/plinko.svg",
    provider: "WG",
    category: "minigames",
    tag: "HOT",
    rating: 4.8,
    playCount: "1.6M",
    supportsFreeSpins: false,
  },
  5001: {
    id: 5001,
    name: "Crash",
    artwork: "/images/games/crash.svg",
    provider: "WG",
    category: "minigames",
    tag: "HOT",
    rating: 4.7,
    playCount: "740K",
    supportsFreeSpins: false,
  },
  312005: {
    id: 312005,
    name: "Mines",
    artwork: "/images/games/mines.svg",
    provider: "Spribe",
    category: "minigames",
    tag: "HOT",
    rating: 4.9,
    playCount: "2.1M",
    supportsFreeSpins: false,
  },
  10280084: {
    id: 10280084,
    name: "Andar Bahar",
    artwork: "/images/games/andar_bahar.svg",
    provider: "KingMidas",
    category: "cards",
    tag: "HOT",
    rating: 4.9,
    playCount: "3.5M",
    supportsFreeSpins: false,
  },
  1016: {
    id: 1016,
    name: "Dragon Tiger",
    artwork: "/images/games/dragon_tiger.svg",
    provider: "WG",
    category: "cards",
    tag: "HOT",
    rating: 4.8,
    playCount: "2.8M",
    supportsFreeSpins: false,
  },
  3150289: {
    id: 3150289,
    name: "Ocean King Jackpot",
    artwork: "/images/games/ocean_king.svg",
    provider: "JILI",
    category: "fishing",
    tag: "JACKPOT",
    rating: 4.8,
    playCount: "1.1M",
    supportsFreeSpins: false,
  },
  3150074: {
    id: 3150074,
    name: "Mega Fishing",
    artwork: "/images/games/mega_fishing.svg",
    provider: "JILI",
    category: "fishing",
    tag: "HOT",
    rating: 4.7,
    playCount: "980K",
    supportsFreeSpins: false,
  },
  317000: {
    id: 317000,
    name: "Evolution Live Roulette",
    artwork: "/images/games/live_roulette.svg",
    provider: "Evolution",
    category: "live",
    tag: "HOT",
    rating: 4.9,
    playCount: "5.2M",
    isMemberOnly: true,
  },
  1012000: {
    id: 1012000,
    name: "SEXY Live Baccarat",
    artwork: "/images/games/sexy_baccarat.svg",
    provider: "SEXY Live",
    category: "live",
    tag: "HOT",
    rating: 4.8,
    playCount: "3.7M",
    isMemberOnly: true,
  },
  1014000: {
    id: 1014000,
    name: "9Wickets Cricket Exchange",
    artwork: "/images/games/9wickets_cricket.svg",
    provider: "9Wickets",
    category: "sports",
    tag: "HOT",
    rating: 4.9,
    playCount: "8.4M",
    isMemberOnly: true,
  },
  328000: {
    id: 328000,
    name: "SABA Sports In-Play",
    artwork: "/images/games/saba_sports.svg",
    provider: "SABA",
    category: "sports",
    tag: "HOT",
    rating: 4.8,
    playCount: "3.1M",
    isMemberOnly: true,
  },
  87000: {
    id: 87000,
    name: "SV388 Cockfight Live",
    artwork: "/images/games/sv388_cockfight.svg",
    provider: "SV388",
    category: "cockfight",
    tag: "HOT",
    rating: 4.6,
    playCount: "420K",
    isMemberOnly: true,
  },
  74000: {
    id: 74000,
    name: "DB E-Sports Arena",
    artwork: "/images/games/db_esports.svg",
    provider: "DB E-Sports",
    category: "esports",
    tag: "NEW",
    rating: 4.7,
    playCount: "310K",
    isMemberOnly: true,
  },
  39000: {
    id: 39000,
    name: "TCG Lottery Quick 3",
    artwork: "/images/games/tcg_lottery.svg",
    provider: "TCG Lottery",
    category: "lottery",
    tag: "NEW",
    rating: 4.5,
    playCount: "190K",
    isMemberOnly: true,
  },
  3150060: {
    id: 3150060,
    name: "Golden Empire",
    artwork: "/images/games/golden_empire.svg",
    provider: "JILI",
    category: "slot",
    tag: "HOT",
    rating: 4.8,
    playCount: "2.1M",
    supportsFreeSpins: true,
  },
  3150080: {
    id: 3150080,
    name: "Boxing King",
    artwork: "/images/games/boxing_king.svg",
    provider: "JILI",
    category: "slot",
    tag: "HOT",
    rating: 4.7,
    playCount: "1.5M",
    supportsFreeSpins: true,
  },
  2000140: {
    id: 2000140,
    name: "Gates of Olympus",
    artwork: "/images/games/gates_of_olympus.svg",
    provider: "Pragmatic Play",
    category: "slot",
    tag: "HOT",
    rating: 4.9,
    playCount: "4.8M",
    supportsFreeSpins: true,
  },
  2000150: {
    id: 2000150,
    name: "Sweet Bonanza",
    artwork: "/images/games/sweet_bonanza.svg",
    provider: "Pragmatic Play",
    category: "slot",
    tag: "HOT",
    rating: 4.9,
    playCount: "3.7M",
    supportsFreeSpins: true,
  },
  317010: {
    id: 317010,
    name: "Crazy Time Live",
    artwork: "/images/games/crazy_time.svg",
    provider: "Evolution",
    category: "live",
    tag: "HOT",
    rating: 4.9,
    playCount: "5.2M",
    isMemberOnly: true,
  },
  317020: {
    id: 317020,
    name: "Lightning Roulette",
    artwork: "/images/games/lightning_roulette.svg",
    provider: "Evolution",
    category: "live",
    tag: "HOT",
    rating: 4.8,
    playCount: "2.8M",
    isMemberOnly: true,
  },
  317030: {
    id: 317030,
    name: "Teen Patti Live",
    artwork: "/images/games/teen_patti_live.svg",
    provider: "Ezugi",
    category: "live",
    tag: "HOT",
    rating: 4.8,
    playCount: "1.9M",
    isMemberOnly: true,
  },
  3150210: {
    id: 3150210,
    name: "Callbreak Champion",
    artwork: "/images/games/callbreak.svg",
    provider: "KingMidas",
    category: "cards",
    tag: "HOT",
    rating: 4.7,
    playCount: "920K",
    supportsFreeSpins: false,
  },
  3150075: {
    id: 3150075,
    name: "Happy Fishing",
    artwork: "/images/games/happy_fishing.svg",
    provider: "JILI",
    category: "fishing",
    tag: "HOT",
    rating: 4.7,
    playCount: "1.1M",
    supportsFreeSpins: false,
  },
  328010: {
    id: 328010,
    name: "BTI Sports Arena",
    artwork: "/images/games/bti_sports.svg",
    provider: "BTI",
    category: "sports",
    tag: "HOT",
    rating: 4.6,
    playCount: "840K",
    isMemberOnly: true,
  },
  312010: {
    id: 312010,
    name: "HiLo Master",
    artwork: "/images/games/hilo.svg",
    provider: "Spribe",
    category: "minigames",
    tag: "NEW",
    rating: 4.6,
    playCount: "630K",
    supportsFreeSpins: false,
  },
  39010: {
    id: 39010,
    name: "Win Go 1 Min",
    artwork: "/images/games/wingo.svg",
    provider: "TCG Lottery",
    category: "lottery",
    tag: "HOT",
    rating: 4.7,
    playCount: "750K",
    isMemberOnly: true,
  },
};

export const DEFAULT_GAME_PLACEHOLDER = "/images/games/game_placeholder.svg";

export function getGameArtwork(gameId: number | string): string {
  const numId = typeof gameId === "string" ? parseInt(gameId, 10) : gameId;
  return GAME_ARTWORK_MAP[numId]?.artwork || DEFAULT_GAME_PLACEHOLDER;
}
