import { Game, GameCategory, BannerSlide, WinnerRecord, Notice, LanguageOption, TaskItem, UserProfile, WalletTransaction } from "@/types/site";

export const CATEGORIES: GameCategory[] = [
  { id: "hot", name: "Hot", iconName: "HotIcon", count: 48, providers: ["All", "JILI", "Spribe", "PG Soft", "WG", "INOUT", "KingMidas"] },
  { id: "sports", name: "Sports", iconName: "SportsIcon", count: 14, providers: ["All", "9Wickets", "SABA", "Lucky", "BTI", "Crown", "FB"] },
  { id: "live", name: "Live Casino", iconName: "LiveCasinoIcon", count: 24, providers: ["All", "Evolution", "SEXY Live", "Ezugi", "WM", "DG", "Playtech"] },
  { id: "minigames", name: "Mini Games", iconName: "MiniGameIcon", count: 32, providers: ["All", "Spribe", "INOUT", "WG", "JILI", "T1", "TURBO", "BGaming"] },
  { id: "slot", name: "Slots", iconName: "SlotIcon", count: 120, providers: ["All", "JILI", "PG Soft", "JDB", "FC", "CQ9", "SmartSoft", "Hacksaw", "NolimitCity"] },
  { id: "cards", name: "Cards", iconName: "CardsIcon", count: 18, providers: ["All", "JILI", "KingMidas", "WG", "Baison", "2J", "BGaming"] },
  { id: "fishing", name: "Fishing", iconName: "FishingIcon", count: 16, providers: ["All", "JILI", "WG", "JDB", "Spade Gaming", "FC", "YellowBat"] },
  { id: "cockfight", name: "Cock Fighting", iconName: "CockfightIcon", count: 4, providers: ["All", "SV388", "GA28"] },
  { id: "esports", name: "E-Sports", iconName: "ESportsIcon", count: 6, providers: ["All", "DB E-Sports", "NEWBBIN", "IA"] },
  { id: "lottery", name: "Lottery", iconName: "LotteryIcon", count: 8, providers: ["All", "TCG Lottery"] },
  { id: "demo", name: "Demo", iconName: "DemoIcon", count: 15, providers: ["All", "JILI", "WG"] },
];

export const GAMES: Game[] = [
  {
    id: 312001,
    name: "Aviator",
    category: "minigames",
    provider: "Spribe",
    thumbnail: "https://images.unsplash.com/photo-1517976487502-5f71e54911d3?w=500&auto=format&fit=crop&q=80",
    tag: "HOT",
    rating: 4.9,
    playCount: "3.2M",
    supportsFreeSpins: false,
  },
  {
    id: 3150300,
    name: "Fortune Gems 3",
    category: "slot",
    provider: "JILI",
    thumbnail: "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=500&auto=format&fit=crop&q=80",
    tag: "HOT",
    rating: 4.8,
    playCount: "1.9M",
    supportsFreeSpins: true,
  },
  {
    id: 3150049,
    name: "Super Ace",
    category: "slot",
    provider: "JILI",
    thumbnail: "https://images.unsplash.com/photo-1511193311914-0346f16efe90?w=500&auto=format&fit=crop&q=80",
    tag: "HOT",
    rating: 4.9,
    playCount: "2.4M",
    supportsFreeSpins: true,
  },
  {
    id: 3150094,
    name: "Rummy",
    category: "cards",
    provider: "JILI",
    thumbnail: "https://images.unsplash.com/photo-1543083477-4f785aeafaa9?w=500&auto=format&fit=crop&q=80",
    tag: "HOT",
    rating: 4.9,
    playCount: "4.1M",
    supportsFreeSpins: false,
  },
  {
    id: 3150124,
    name: "7up 7down",
    category: "cards",
    provider: "JILI",
    thumbnail: "https://images.unsplash.com/photo-1533227268428-f9ed0900fb3b?w=500&auto=format&fit=crop&q=80",
    tag: "NEW",
    rating: 4.7,
    playCount: "890K",
    supportsFreeSpins: false,
  },
  {
    id: 3150200,
    name: "PAPPU",
    category: "cards",
    provider: "JILI",
    thumbnail: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=500&auto=format&fit=crop&q=80",
    tag: "HOT",
    rating: 4.6,
    playCount: "650K",
    supportsFreeSpins: false,
  },
  {
    id: 3150051,
    name: "Money Coming",
    category: "slot",
    provider: "JILI",
    thumbnail: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=500&auto=format&fit=crop&q=80",
    tag: "JACKPOT",
    rating: 4.9,
    playCount: "5.8M",
    supportsFreeSpins: true,
  },
  {
    id: 2000135,
    name: "Wild Bounty Showdown",
    category: "slot",
    provider: "PG Soft",
    thumbnail: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500&auto=format&fit=crop&q=80",
    tag: "HOT",
    rating: 4.8,
    playCount: "1.2M",
    supportsFreeSpins: false,
  },
  {
    id: 3660003,
    name: "Chicken Road 2.0",
    category: "minigames",
    provider: "INOUT",
    thumbnail: "https://images.unsplash.com/photo-1548247416-ec66f4900b2e?w=500&auto=format&fit=crop&q=80",
    tag: "NEW",
    rating: 4.9,
    playCount: "950K",
    supportsFreeSpins: false,
  },
  {
    id: 3660008,
    name: "Chicken Road",
    category: "minigames",
    provider: "INOUT",
    thumbnail: "https://images.unsplash.com/photo-1563281577-a7be47e20db9?w=500&auto=format&fit=crop&q=80",
    tag: "HOT",
    rating: 4.7,
    playCount: "820K",
    supportsFreeSpins: false,
  },
  {
    id: 5008,
    name: "Plinko",
    category: "minigames",
    provider: "WG",
    thumbnail: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=500&auto=format&fit=crop&q=80",
    tag: "HOT",
    rating: 4.8,
    playCount: "1.6M",
    supportsFreeSpins: false,
  },
  {
    id: 5001,
    name: "Crash",
    category: "minigames",
    provider: "WG",
    thumbnail: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=500&auto=format&fit=crop&q=80",
    tag: "HOT",
    rating: 4.7,
    playCount: "740K",
    supportsFreeSpins: false,
  },
  {
    id: 312005,
    name: "Mines",
    category: "minigames",
    provider: "Spribe",
    thumbnail: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=500&auto=format&fit=crop&q=80",
    tag: "HOT",
    rating: 4.9,
    playCount: "2.1M",
    supportsFreeSpins: false,
  },
  {
    id: 10280084,
    name: "Andar Bahar",
    category: "cards",
    provider: "KingMidas",
    thumbnail: "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=500&auto=format&fit=crop&q=80",
    tag: "HOT",
    rating: 4.9,
    playCount: "3.5M",
    supportsFreeSpins: false,
  },
  {
    id: 1016,
    name: "Dragon Tiger",
    category: "cards",
    provider: "WG",
    thumbnail: "https://images.unsplash.com/photo-1563245372-f21724e3856d?w=500&auto=format&fit=crop&q=80",
    tag: "HOT",
    rating: 4.8,
    playCount: "2.8M",
    supportsFreeSpins: false,
  },
  {
    id: 3150289,
    name: "Ocean King Jackpot",
    category: "fishing",
    provider: "JILI",
    thumbnail: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=500&auto=format&fit=crop&q=80",
    tag: "JACKPOT",
    rating: 4.8,
    playCount: "1.1M",
    supportsFreeSpins: false,
  },
  {
    id: 3150074,
    name: "Mega Fishing",
    category: "fishing",
    provider: "JILI",
    thumbnail: "https://images.unsplash.com/photo-1522069169874-c58ec4b76be5?w=500&auto=format&fit=crop&q=80",
    tag: "HOT",
    rating: 4.7,
    playCount: "980K",
    supportsFreeSpins: false,
  },
  {
    id: 317000,
    name: "Evolution Live Roulette",
    category: "live",
    provider: "Evolution",
    thumbnail: "https://images.unsplash.com/photo-1606167668584-78701c57f13d?w=500&auto=format&fit=crop&q=80",
    tag: "HOT",
    rating: 4.9,
    playCount: "5.2M",
    isMemberOnly: true,
  },
  {
    id: 1012000,
    name: "SEXY Live Baccarat",
    category: "live",
    provider: "SEXY Live",
    thumbnail: "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=500&auto=format&fit=crop&q=80",
    tag: "HOT",
    rating: 4.8,
    playCount: "3.7M",
    isMemberOnly: true,
  },
  {
    id: 1014000,
    name: "9Wickets Cricket Exchange",
    category: "sports",
    provider: "9Wickets",
    thumbnail: "https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=500&auto=format&fit=crop&q=80",
    tag: "HOT",
    rating: 4.9,
    playCount: "8.4M",
    isMemberOnly: true,
  },
  {
    id: 328000,
    name: "SABA Sports In-Play",
    category: "sports",
    provider: "SABA",
    thumbnail: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=500&auto=format&fit=crop&q=80",
    tag: "HOT",
    rating: 4.8,
    playCount: "3.1M",
    isMemberOnly: true,
  },
  {
    id: 87000,
    name: "SV388 Cockfight Live",
    category: "cockfight",
    provider: "SV388",
    thumbnail: "https://images.unsplash.com/photo-1548247416-ec66f4900b2e?w=500&auto=format&fit=crop&q=80",
    tag: "HOT",
    rating: 4.6,
    playCount: "420K",
    isMemberOnly: true,
  },
  {
    id: 74000,
    name: "DB E-Sports Arena",
    category: "esports",
    provider: "DB E-Sports",
    thumbnail: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=500&auto=format&fit=crop&q=80",
    tag: "NEW",
    rating: 4.7,
    playCount: "310K",
    isMemberOnly: true,
  },
  {
    id: 39000,
    name: "TCG Lottery Quick 3",
    category: "lottery",
    provider: "TCG Lottery",
    thumbnail: "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=500&auto=format&fit=crop&q=80",
    tag: "NEW",
    rating: 4.5,
    playCount: "190K",
    isMemberOnly: true,
  }
];

export const BANNERS: BannerSlide[] = [
  {
    id: 1,
    title: "Super VIP Tier Rewards",
    subtitle: "Unlock exclusive VIP privileges, faster demo processing, weekly tier bonuses & custom avatar frames",
    badge: "VIP CLUB",
    ctaText: "Explore VIP Levels",
    bgGradient: "from-[#2A1E00] via-[#1A1A1A] to-[#0A0A0A]",
    imageUrl: "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=1200&auto=format&fit=crop&q=80",
  },
  {
    id: 2,
    title: "Registration 111 ₹ Starter Bonus",
    subtitle: "Sign up today with your phone number and get ₹111 free demo credits credited to your account!",
    badge: "NEW MEMBER",
    ctaText: "Register Now",
    bgGradient: "from-[#3B1200] via-[#1F1005] to-[#0A0A0A]",
    imageUrl: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=1200&auto=format&fit=crop&q=80",
  },
  {
    id: 3,
    title: "Daily Tasks & Earn Free Spins",
    subtitle: "Complete easy daily tasks to earn genuine free spins on Fortune Gems 3, Super Ace and Money Coming!",
    badge: "TASKS & REWARDS",
    ctaText: "View Daily Tasks",
    bgGradient: "from-[#0E2413] via-[#121B14] to-[#0A0A0A]",
    imageUrl: "https://images.unsplash.com/photo-1511193311914-0346f16efe90?w=1200&auto=format&fit=crop&q=80",
  },
  {
    id: 4,
    title: "Aviator & Chicken Road 2.0 Challenge",
    subtitle: "Test your prediction skill in real-time crash multiplier games with interactive demo gameplay",
    badge: "CRASH MINI GAMES",
    ctaText: "Play Demo Games",
    bgGradient: "from-[#261533] via-[#17121D] to-[#0A0A0A]",
    imageUrl: "https://images.unsplash.com/photo-1606167668584-78701c57f13d?w=1200&auto=format&fit=crop&q=80",
  }
];

export const WINNERS: WinnerRecord[] = [
  { id: "1", userId: "player_9***2", gameName: "Money Coming", amount: 505, currency: "₹", provider: "JILI", timestamp: "2m ago" },
  { id: "2", userId: "demo_user3***7", gameName: "Super Ace", amount: 119, currency: "₹", provider: "JILI", timestamp: "4m ago" },
  { id: "3", userId: "player_3***4", gameName: "Fortune Gems 3", amount: 71, currency: "₹", provider: "JILI", timestamp: "6m ago" },
  { id: "4", userId: "player_2***9", gameName: "Ocean King Jackpot", amount: 2018, currency: "₹", provider: "JILI", timestamp: "9m ago" },
  { id: "5", userId: "guest_1***2", gameName: "Money Coming", amount: 5001, currency: "₹", provider: "JILI", timestamp: "12m ago" },
  { id: "6", userId: "player_2***4", gameName: "Super Ace", amount: 79.5, currency: "₹", provider: "JILI", timestamp: "15m ago" },
  { id: "7", userId: "demo_7***1", gameName: "Money Coming", amount: 1990, currency: "₹", provider: "JILI", timestamp: "18m ago" },
  { id: "8", userId: "player_2***2", gameName: "Fortune Gems 3", amount: 495, currency: "₹", provider: "JILI", timestamp: "21m ago" },
  { id: "9", userId: "player_6***1", gameName: "Super Ace", amount: 102.3, currency: "₹", provider: "JILI", timestamp: "24m ago" },
  { id: "10", userId: "aviator_pro***0", gameName: "Aviator", amount: 14200, currency: "₹", provider: "Spribe", timestamp: "28m ago" },
  { id: "11", userId: "demo_8***7", gameName: "Chicken Road 2.0", amount: 3450, currency: "₹", provider: "INOUT", timestamp: "32m ago" },
  { id: "12", userId: "rummy_fan***1", gameName: "Rummy", amount: 8900, currency: "₹", provider: "JILI", timestamp: "35m ago" },
];

export const NOTICES: Notice[] = [
  {
    id: 1,
    title: "IPLwin Gaming Platform v2.0 Live",
    content: "Welcome to the upgraded IPLwin Gaming Experience. Enjoy ultra-smooth navigation, interactive demo games, and our new Tasks & Rewards Hub.",
    date: "2026-10-01"
  },
  {
    id: 2,
    title: "Earn Free Spins in Daily Tasks Hub",
    content: "Free spins are not granted automatically — complete daily check-ins and gameplay tasks in the Rewards section to earn genuine free spins for Super Ace and Fortune Gems 3!",
    date: "2026-10-01"
  },
  {
    id: 3,
    title: "Simulated Entertainment Mode Notice",
    content: "All demo balances, chips, and simulated games are intended solely for testing, demonstration, and gaming entertainment. Please enjoy responsibly.",
    date: "2026-09-30"
  }
];

export const LANGUAGES: LanguageOption[] = [
  { code: "en", name: "English", nativeName: "English", flag: "🇬🇧" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी", flag: "🇮🇳" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు", flag: "🇮🇳" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்", flag: "🇮🇳" },
  { code: "mr", name: "Marathi", nativeName: "मराठी", flag: "🇮🇳" },
  { code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ", flag: "🇮🇳" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা", flag: "🇮🇳" },
  { code: "pa", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ", flag: "🇮🇳" },
];

export const INITIAL_TASKS: TaskItem[] = [
  {
    id: "task_checkin",
    title: "Daily Check-in",
    description: "Sign in today to claim 3 Free Spins on Fortune Gems 3",
    rewardType: "free_spins",
    rewardAmount: 3,
    targetGameId: 3150300,
    targetGameName: "Fortune Gems 3",
    icon: "📅",
    progress: 1,
    maxProgress: 1,
    claimed: false,
  },
  {
    id: "task_play3",
    title: "Play 3 Demo Rounds",
    description: "Play at least 3 rounds in any demo game to unlock 6 Free Spins on Super Ace",
    rewardType: "free_spins",
    rewardAmount: 6,
    targetGameId: 3150049,
    targetGameName: "Super Ace",
    icon: "🎮",
    progress: 1,
    maxProgress: 3,
    claimed: false,
  },
  {
    id: "task_aviator",
    title: "Fly in Aviator Demo",
    description: "Launch Aviator demo and achieve a multiplier of 2.0x or higher",
    rewardType: "demo_cash",
    rewardAmount: 50,
    icon: "🚀",
    progress: 0,
    maxProgress: 1,
    claimed: false,
  },
  {
    id: "task_deposit_demo",
    title: "Try Demo Wallet Top-up",
    description: "Simulate a demo recharge in your wallet to earn 5 Free Spins on Money Coming",
    rewardType: "free_spins",
    rewardAmount: 5,
    targetGameId: 3150051,
    targetGameName: "Money Coming",
    icon: "💳",
    progress: 0,
    maxProgress: 1,
    claimed: false,
  },
];

export const DEFAULT_GUEST_USER: UserProfile = {
  id: "guest",
  username: "Guest Player",
  phone: "",
  balance: 0,
  vipLevel: 0,
  avatar: "👤",
  isLoggedIn: false,
  earnedFreeSpins: {}, // Rule 13: Free spins are NOT default! They are empty until earned from tasks.
  completedTasks: [],
};

export const INITIAL_TRANSACTIONS: WalletTransaction[] = [
  {
    id: "tx_welcome",
    type: "task_reward",
    amount: 111,
    title: "New Member Starter Demo Bonus",
    timestamp: "Just now",
    status: "completed",
  },
];
