import { Game, GameCategory, BannerSlide, WinnerRecord, Notice, LanguageOption } from "@/types/site";

export const CATEGORIES: GameCategory[] = [
  { id: "hot", name: "Hot", iconName: "HotIcon", count: 48, providers: ["All", "JILI", "Spribe", "PG Soft", "WG", "INOUT", "KingMidas"] },
  { id: "sports", name: "Sports", iconName: "SportsIcon", count: 14, providers: ["All", "9Wickets", "SABA", "Lucky", "BTI", "Crown", "FB"] },
  { id: "live", name: "Live Casino", iconName: "LiveCasinoIcon", count: 24, providers: ["All", "Evolution", "SEXY Live", "Ezugi", "WM", "DG", "Playtech"] },
  { id: "minigames", name: "Mini Games", iconName: "MiniGameIcon", count: 32, providers: ["All", "Spribe", "INOUT", "WG", "JILI", "T1", "TURBO", "BGaming"] },
  { id: "slot", name: "Slots", iconName: "SlotIcon", count: 120, providers: ["All", "JILI", "PG Soft", "JDB", "FC", "CQ9", "SmartSoft", "Hacksaw", "NolimitCity"] },
  { id: "cards", name: "Cards", iconName: "CardsIcon", count: 18, providers: ["All", "JILI", "KingMidas", "WG", "Baison", "2J", "BGaming"] },
  { id: "fishing", name: "Fishing", iconName: "FishingIcon", count: 16, providers: ["All", "JILI", "WG", "JDB", "Spade Gaming", "FC", "YellowBat"] },
  { id: "cockfight", name: "Cock Fighting", iconName: "CockfightIcon", count: 4, providers: ["All", "SV388", "GA28"] },
  { id: "esports", name: "E-Sports", iconName: "ESportsIcon", count: 6, providers: ["All", "DB E-Sports", "NEWBBIN", "IA"] },
  { id: "lottery", name: "Lottery", iconName: "LotteryIcon", count: 8, providers: ["All", "TCG Lottery"] },
  { id: "demo", name: "Demo", iconName: "DemoIcon", count: 15, providers: ["All", "JILI", "WG"] },
];

export const GAMES: Game[] = [
  {
    id: 312001,
    name: "Aviator",
    category: "minigames",
    provider: "Spribe",
    thumbnail: "https://images.unsplash.com/photo-1517976487502-5f71e54911d3?w=500&auto=format&fit=crop&q=80",
    tag: "HOT",
    rating: 4.9,
    playCount: "3.2M",
  },
  {
    id: 3150300,
    name: "Fortune Gems 3",
    category: "slot",
    provider: "JILI",
    thumbnail: "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=500&auto=format&fit=crop&q=80",
    tag: "HOT",
    rating: 4.8,
    playCount: "1.9M",
  },
  {
    id: 3150049,
    name: "Super Ace",
    category: "slot",
    provider: "JILI",
    thumbnail: "https://images.unsplash.com/photo-1511193311914-0346f16efe90?w=500&auto=format&fit=crop&q=80",
    tag: "HOT",
    rating: 4.9,
    playCount: "2.4M",
  },
  {
    id: 3150094,
    name: "Rummy",
    category: "cards",
    provider: "JILI",
    thumbnail: "https://images.unsplash.com/photo-1543083477-4f785aeafaa9?w=500&auto=format&fit=crop&q=80",
    tag: "HOT",
    rating: 4.9,
    playCount: "4.1M",
  },
  {
    id: 3150124,
    name: "7up 7down",
    category: "cards",
    provider: "JILI",
    thumbnail: "https://images.unsplash.com/photo-1533227268428-f9ed0900fb3b?w=500&auto=format&fit=crop&q=80",
    tag: "NEW",
    rating: 4.7,
    playCount: "890K",
  },
  {
    id: 3150200,
    name: "PAPPU",
    category: "cards",
    provider: "JILI",
    thumbnail: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=500&auto=format&fit=crop&q=80",
    tag: "HOT",
    rating: 4.6,
    playCount: "650K",
  },
  {
    id: 3150051,
    name: "Money Coming",
    category: "slot",
    provider: "JILI",
    thumbnail: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=500&auto=format&fit=crop&q=80",
    tag: "JACKPOT",
    rating: 4.9,
    playCount: "5.8M",
  },
  {
    id: 2000135,
    name: "Wild Bounty Showdown",
    category: "slot",
    provider: "PG Soft",
    thumbnail: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500&auto=format&fit=crop&q=80",
    tag: "HOT",
    rating: 4.8,
    playCount: "1.2M",
  },
  {
    id: 3660003,
    name: "Chicken Road 2.0",
    category: "minigames",
    provider: "INOUT",
    thumbnail: "https://images.unsplash.com/photo-1548247416-ec66f4900b2e?w=500&auto=format&fit=crop&q=80",
    tag: "NEW",
    rating: 4.9,
    playCount: "950K",
  },
  {
    id: 3660008,
    name: "Chicken Road",
    category: "minigames",
    provider: "INOUT",
    thumbnail: "https://images.unsplash.com/photo-1563281577-a7be47e20db9?w=500&auto=format&fit=crop&q=80",
    tag: "HOT",
    rating: 4.7,
    playCount: "820K",
  },
  {
    id: 5008,
    name: "Plinko",
    category: "minigames",
    provider: "WG",
    thumbnail: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=500&auto=format&fit=crop&q=80",
    tag: "HOT",
    rating: 4.8,
    playCount: "1.6M",
  },
  {
    id: 5001,
    name: "Crash",
    category: "minigames",
    provider: "WG",
    thumbnail: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=500&auto=format&fit=crop&q=80",
    tag: "HOT",
    rating: 4.7,
    playCount: "740K",
  },
  {
    id: 312005,
    name: "Mines",
    category: "minigames",
    provider: "Spribe",
    thumbnail: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=500&auto=format&fit=crop&q=80",
    tag: "HOT",
    rating: 4.9,
    playCount: "2.1M",
  },
  {
    id: 10280084,
    name: "Andar Bahar",
    category: "cards",
    provider: "KingMidas",
    thumbnail: "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=500&auto=format&fit=crop&q=80",
    tag: "HOT",
    rating: 4.9,
    playCount: "3.5M",
  },
  {
    id: 1016,
    name: "Dragon Tiger",
    category: "cards",
    provider: "WG",
    thumbnail: "https://images.unsplash.com/photo-1563245372-f21724e3856d?w=500&auto=format&fit=crop&q=80",
    tag: "HOT",
    rating: 4.8,
    playCount: "2.8M",
  },
  {
    id: 3150289,
    name: "Ocean King Jackpot",
    category: "fishing",
    provider: "JILI",
    thumbnail: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=500&auto=format&fit=crop&q=80",
    tag: "JACKPOT",
    rating: 4.8,
    playCount: "1.1M",
  },
  {
    id: 3150074,
    name: "Mega Fishing",
    category: "fishing",
    provider: "JILI",
    thumbnail: "https://images.unsplash.com/photo-1522069169874-c58ec4b76be5?w=500&auto=format&fit=crop&q=80",
    tag: "HOT",
    rating: 4.7,
    playCount: "980K",
  },
  {
    id: 317000,
    name: "Evolution Live Roulette",
    category: "live",
    provider: "Evolution",
    thumbnail: "https://images.unsplash.com/photo-1606167668584-78701c57f13d?w=500&auto=format&fit=crop&q=80",
    tag: "HOT",
    rating: 4.9,
    playCount: "5.2M",
  },
  {
    id: 1012000,
    name: "SEXY Live Baccarat",
    category: "live",
    provider: "SEXY Live",
    thumbnail: "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=500&auto=format&fit=crop&q=80",
    tag: "HOT",
    rating: 4.8,
    playCount: "3.7M",
  },
  {
    id: 1014000,
    name: "9Wickets Cricket Exchange",
    category: "sports",
    provider: "9Wickets",
    thumbnail: "https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=500&auto=format&fit=crop&q=80",
    tag: "HOT",
    rating: 4.9,
    playCount: "8.4M",
  },
  {
    id: 328000,
    name: "SABA Sports In-Play",
    category: "sports",
    provider: "SABA",
    thumbnail: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=500&auto=format&fit=crop&q=80",
    tag: "HOT",
    rating: 4.8,
    playCount: "3.1M",
  },
  {
    id: 87000,
    name: "SV388 Cockfight Live",
    category: "cockfight",
    provider: "SV388",
    thumbnail: "https://images.unsplash.com/photo-1548247416-ec66f4900b2e?w=500&auto=format&fit=crop&q=80",
    tag: "HOT",
    rating: 4.6,
    playCount: "420K",
  },
  {
    id: 74000,
    name: "DB E-Sports Arena",
    category: "esports",
    provider: "DB E-Sports",
    thumbnail: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=500&auto=format&fit=crop&q=80",
    tag: "NEW",
    rating: 4.7,
    playCount: "310K",
  },
  {
    id: 39000,
    name: "TCG Lottery Quick 3",
    category: "lottery",
    provider: "TCG Lottery",
    thumbnail: "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=500&auto=format&fit=crop&q=80",
    tag: "NEW",
    rating: 4.5,
    playCount: "190K",
  }
];

export const BANNERS: BannerSlide[] = [
  {
    id: 1,
    title: "Super VIP 111,111 ₹ Bonus",
    subtitle: "Level up your status with weekly cashback, luxury birthday gifts & 24/7 personal VIP manager",
    badge: "VIP EXCLUSIVE",
    ctaText: "Claim VIP Bonus",
    bgGradient: "from-[#2A1E00] via-[#1A1A1A] to-[#0A0A0A]",
    imageUrl: "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=1200&auto=format&fit=crop&q=80",
  },
  {
    id: 2,
    title: "Registration 111 ₹ Instant Bonus",
    subtitle: "Sign up today with your mobile number and receive ₹111 free trial balance with no deposit required!",
    badge: "NEW MEMBER",
    ctaText: "Register Now",
    bgGradient: "from-[#3B1200] via-[#1F1005] to-[#0A0A0A]",
    imageUrl: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=1200&auto=format&fit=crop&q=80",
  },
  {
    id: 3,
    title: "Lucky Wheel Points Giveaway",
    subtitle: "Deposit daily to spin the gold fortune wheel — 100% win rate up to ₹150,000 real cash prizes",
    badge: "DAILY REWARD",
    ctaText: "Spin The Wheel",
    bgGradient: "from-[#0E2413] via-[#121B14] to-[#0A0A0A]",
    imageUrl: "https://images.unsplash.com/photo-1511193311914-0346f16efe90?w=1200&auto=format&fit=crop&q=80",
  },
  {
    id: 4,
    title: "Bank Card 1.5% Unlimited Cashback",
    subtitle: "Every deposit made through UPI, PhonePe, Paytm or NetBanking receives instant 1.5% extra bonus",
    badge: "DEPOSIT REBATE",
    ctaText: "Deposit Now",
    bgGradient: "from-[#261533] via-[#17121D] to-[#0A0A0A]",
    imageUrl: "https://images.unsplash.com/photo-1606167668584-78701c57f13d?w=1200&auto=format&fit=crop&q=80",
  }
];

export const WINNERS: WinnerRecord[] = [
  { id: "1", userId: "9***02", gameName: "Money Coming", amount: 505, currency: "₹", provider: "JILI" },
  { id: "2", userId: "3***87", gameName: "Super Ace", amount: 119, currency: "₹", provider: "JILI" },
  { id: "3", userId: "3***14", gameName: "Fortune Gems 3", amount: 71, currency: "₹", provider: "JILI" },
  { id: "4", userId: "2***99", gameName: "Ocean King Jackpot", amount: 2018, currency: "₹", provider: "JILI" },
  { id: "5", userId: "1***12", gameName: "Money Coming", amount: 5001, currency: "₹", provider: "JILI" },
  { id: "6", userId: "2***44", gameName: "Super Ace", amount: 79.5, currency: "₹", provider: "JILI" },
  { id: "7", userId: "7***81", gameName: "Money Coming", amount: 1990, currency: "₹", provider: "JILI" },
  { id: "8", userId: "2***72", gameName: "Fortune Gems 3", amount: 495, currency: "₹", provider: "JILI" },
  { id: "9", userId: "6***11", gameName: "Super Ace", amount: 102.3, currency: "₹", provider: "JILI" },
  { id: "10", userId: "5***30", gameName: "Aviator", amount: 14200, currency: "₹", provider: "Spribe" },
  { id: "11", userId: "8***67", gameName: "Chicken Road 2.0", amount: 3450, currency: "₹", provider: "INOUT" },
  { id: "12", userId: "4***91", gameName: "Rummy", amount: 8900, currency: "₹", provider: "JILI" },
];

export const NOTICES: Notice[] = [
  {
    id: 1,
    title: "IPLwin Lucky Bonus is Live!",
    content: "The IPLwin Lucky Bonus is now live! 🎉 All users with a withdrawal record have a chance to win prizes ranging from 50,000 to 150,000 RS. Winners will be announced via in-site messages and pop-up notifications.",
    date: "2026-10-01"
  },
  {
    id: 2,
    title: "Fast Withdrawal Guarantee",
    content: "IPLwin is committed to providing customers with a seamless and hassle-free experience. All player transactions are completed within 3 minutes. We provide safe, reliable and fast deposit and withdrawal services around the clock.",
    date: "2026-09-30"
  },
  {
    id: 3,
    title: "Official Channel & Telegram Notices",
    content: "Please beware of impersonators. IPLwin's official customer support and bonus channels are only verified through our official web application and verified Telegram channel @iplwin_official.",
    date: "2026-09-28"
  }
];

export const LANGUAGES: LanguageOption[] = [
  { code: "en", name: "English", nativeName: "English", flag: "🇬🇧" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी", flag: "🇮🇳" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు", flag: "🇮🇳" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்", flag: "🇮🇳" },
  { code: "mr", name: "Marathi", nativeName: "मराठी", flag: "🇮🇳" },
  { code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ", flag: "🇮🇳" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা", flag: "🇮🇳" },
  { code: "pa", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ", flag: "🇮🇳" },
];
